## Python libraries for Data cleaning

In [2]:
import pandas as pd

In [63]:
df = pd.read_csv("data.tsv.txt", sep= "\t")
df

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

In [95]:
 Item_Price = df["item_price"].str.replace('$', '')

In [98]:
Item_Price = pd.to_numeric(Item_Price)

In [103]:
df["item_price"]=Item_Price

In [108]:
df["total_selling_value"]
df

,order_id,quantity,item_name,choice_description,item_price,total_selling_value
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39,0
1,1,1,Izze,[Clementine],3.39,0
2,1,1,Nantucket Nectar,[Apple],3.39,0
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39,0
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98,0
...,...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",11.75,0
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",11.75,0
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",11.25,0
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",8.75,0
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",8.75,0

In [126]:
df[["item_name","item_price"]]

                                  item_name  item_price
0              Chips and Fresh Tomato Salsa        2.39
1                                      Izze        3.39
2                          Nantucket Nectar        3.39
3     Chips and Tomatillo-Green Chili Salsa        2.39
4                              Chicken Bowl       16.98
...                                     ...         ...
4617                          Steak Burrito       11.75
4618                          Steak Burrito       11.75
4619                     Chicken Salad Bowl       11.25
4620                     Chicken Salad Bowl        8.75
4621                     Chicken Salad Bowl        8.75

[4622 rows x 2 columns]

In [64]:
restaurant_data.isnull().sum()

order_id                 0
quantity                 0
item_name                0
choice_description    1246
item_price               0
dtype: int64

In [65]:
df.describe(include='all')

           order_id     quantity     item_name choice_description item_price
count   4622.000000  4622.000000          4622               3376       4622
unique          NaN          NaN            50               1043         78
top             NaN          NaN  Chicken Bowl        [Diet Coke]     $8.75
freq            NaN          NaN           726                134        730
mean     927.254868     1.075725           NaN                NaN        NaN
std      528.890796     0.410186           NaN                NaN        NaN
min        1.000000     1.000000           NaN                NaN        NaN
25%      477.250000     1.000000           NaN                NaN        NaN
50%      926.000000     1.000000           NaN                NaN        NaN
75%     1393.000000     1.000000           NaN                NaN        NaN
max     1834.000000    15.000000           NaN                NaN        NaN

In [13]:
## Question framing

#### Top 5 selling items of the restuarant

In [66]:
top_selling_items= df.groupby(by="item_name")["quantity"].sum()

In [45]:
top_items = top_selling_items.sort_values(ascending = False ).head()
top_items

item_name
Chicken Bowl           761
Chicken Burrito        591
Chips and Guacamole    506
Steak Burrito          386
Canned Soft Drink      351
Name: quantity, dtype: int64

In [46]:
least_items = top_selling_items.sort_values().head()
least_items

item_name
Carnitas Salad                       1
Chips and Mild Fresh Tomato Salsa    1
Veggie Crispy Tacos                  1
Crispy Tacos                         2
Salad                                2
Name: quantity, dtype: int64

In [127]:
## revenue of top selling items:

top_selling_items_revenue= df.groupby(by="item_name")[["quantity","item_price"]]

In [128]:
top_selling_items_revenue

In [124]:
top_selling_items_revenue.sort_values("quantity",ascending = False)

                                       quantity  item_price
item_name
Chicken Bowl                                761     7342.73
Chicken Burrito                             591     5575.82
Chips and Guacamole                         506     2201.04
Steak Burrito                               386     3851.43
Canned Soft Drink                           351      438.75
Chips                                       230      494.34
Steak Bowl                                  221     2260.19
Bottled Water                               211      302.56
Chips and Fresh Tomato Salsa                130      361.36
Canned Soda                                 126      137.34
Chicken Salad Bowl                          123     1228.75
Chicken Soft Tacos                          120     1108.09
Side of Chips                               110      185.90
Veggie Burrito                               97      934.77
Barbacoa Burrito                             91      894.75
Veggie Bowl                                  87      867.99
Carnitas Bowl                                71      736.71
Barbacoa Bowl                                66      672.36
Carnitas Burrito                             60      597.83
Steak Soft Tacos                             56      536.05
6 Pack Soft Drink                            55      356.95
Chicken Crispy Tacos                         50      472.13
Chips and Tomatillo Red Chili Salsa          50      147.50
Chips and Tomatillo Green Chili Salsa        45      132.75
Carnitas Soft Tacos                          40      375.94
Steak Crispy Tacos                           36      357.34
Chips and Tomatillo-Green Chili Salsa        33       78.87
Steak Salad Bowl                             31      343.59
Nantucket Nectar                             29       98.31
Chips and Tomatillo-Red Chili Salsa          25       59.75
Barbacoa Soft Tacos                          25      250.46
Chips and Roasted Chili Corn Salsa           23       67.85
Izze                                         20       67.80
Veggie Salad Bowl                            18      182.50
Chips and Roasted Chili-Corn Salsa           18       43.02
Barbacoa Crispy Tacos                        12      120.21
Barbacoa Salad Bowl                          10      106.40
Chicken Salad                                 9       81.09
Carnitas Crispy Tacos                         8       77.96
Veggie Soft Tacos                             8       73.96
Burrito                                       6       44.40
Carnitas Salad Bowl                           6       66.34
Veggie Salad                                  6       50.94
Bowl                                          4       29.60
Steak Salad                                   4       35.66
Salad                                         2       14.80
Crispy Tacos                                  2       14.80
Carnitas Salad                                1        8.99
Chips and Mild Fresh Tomato Salsa             1        3.00
Veggie Crispy Tacos                           1        8.49