## Create 3 data frames using pandas

In [1]:
import pandas as pd

In [48]:
## 1 

top_students_marks = {
    'Student1': {'Name': 'sen', 'Age': 28, 'Grade': 'A'},
    'Student2': {'Name': 'reena', 'Age': 24, 'Grade': 'B'},
    'Student3': {'Name': 'antony', 'Age': 32, 'Grade': 'A'}
}


table_1 = pd.DataFrame(top_students_marks)
table_1

      Student1 Student2 Student3
Name       sen    reena   antony
Age         28       24       32
Grade        A        B        A

In [68]:
## 2

employee_details = {
    'emplyoyee_1':{'Name':'Rajesh','Age':29,'Department':'Ops'},
    'emplyoyee_2':{'Name':'Nasir','Age':31,'Department':'IT Tech'},    
    'emplyoyee_3':{'Name':'Mathiew','Age':30,'Department':'Support'},
    'emplyoyee_4':{'Name':'Gilbert','Age':29,'Department':'Ops'},
    'emplyoyee_5':{'Name':'Kevin','Age':28,'Department':'Support'},
    'emplyoyee_6':{'Name':'Navin','Age':35,'Department':'Support'},
}

table_2 = pd.DataFrame(employee_details)
table_2

,emplyoyee_1,emplyoyee_2,emplyoyee_3,emplyoyee_4,emplyoyee_5,emplyoyee_6
Name,Rajesh,Nasir,Mathiew,Gilbert,Kevin,Navin
Age,29,31,30,29,28,35
Department,Ops,IT Tech,Support,Ops,Support,Support

In [74]:
import pandas as pd

## 3

employee_details_1 = {
                   'Name': ['Rajesh','Nasir','Mathiew','Gilbert','Kevin','Navin'],
                   'Age': [29,31,30,29,28,35],
                   'Department': ['Ops','IT Tech','Support','Ops','Support','Support']
                    }
                    
table_3 = pd.DataFrame(employee_details_1)
table_3

      Name  Age Department
0   Rajesh   29        Ops
1    Nasir   31    IT Tech
2  Mathiew   30    Support
3  Gilbert   29        Ops
4    Kevin   28    Support
5    Navin   35    Support